### ISSUE TITLE
格式不太符合西工大要求，请问如何修改？

### ISSUE THREAD

**Issue by wyk-qyf** [lrtfm/nputhesis#1]
希望继续完善

**Comment by lrtfm** [comment]
有时间会继续更新的，有建议和问题请发issues。

**Comment by wyk-qyf** [comment]
1. 请问您这个模板最后能否通过西工大的论文审核？若能，我就用这个模板写了。因为我不会修改格式，只会添加内容，所以想确认下您的模板格式是否符合西工大的论文要求？
2. 是否有人用您的模板顺利完成论文审核，期待您的回复，谢谢

**Comment by wyk-qyf** [comment]
#2 请查看 @lrtfm

**Comment by lrtfm** [comment]
部分修改请参看 #2 的回复
