### ISSUE TITLE
PDF知网查重乱码

### ISSUE THREAD

**Issue by TsingQAQ** [lrtfm/nputhesis#10]
感谢大佬的分享，Latex小白查了一次重分享一下血泪教训。
知网查重上传的PDF是好的，然后下载下来全是乱码，乱码篇幅占了全文的至少70%， 基本查重废了QAQ
所以可能得转word查。
学校要求上传PDF查重，瑟瑟发抖。

**Comment by lrtfm** [comment]
@TsingQAQ  你好, 请问你说的下载下来是乱码指的是查重报告吗? 还是论文本身?

**Comment by TsingQAQ** [comment]
> @TsingQAQ 你好, 请问你说的下载下来是乱码指的是查重报告吗? 还是论文本身?

查重报告里面的论文部分。
查重报告内含有论文本身和相应查重标记，以告知使用者哪些部分产生了重复，而论文本身在查重报告里几乎全是乱码。

**Comment by lrtfm** [comment]
谢谢. 另外我还有几个问题: 首先论文本身的 pdf 的内容是否可以复制, 即复制pdf的文字到其他地方是否出现乱码? 另外, tex
源文件的编码格式是什么?编译命令用了xelatex or pdflatex?

Qing jixiang <notifications@github.com> 于2019年9月29日周日 上午1:15写道：

**Comment by TsingQAQ** [comment]
抱歉回复较晚:因为我已毕业很长时间，之前写毕设的笔记本没在身边，有些细节记不清楚了，尝试回答您的问题:
首先论文本身的 pdf 的内容是否可以复制, 即复制pdf的文字到其他地方是否出现乱码?
大部分文字可以复制，英文，公式，括号等不可以(我觉得是正常的)
tex源文件的编码格式是什么?编译命令用了xelatex or pdflatex?
我是使用的TexStudio及miktex(应该是)进行编译的，具体的编译格式我不是很清楚


    Yang Zongze <notifications@github.com> 于 2019年9月29日星期日 GMT+2 上午12:53:30写道：  
 
 谢谢. 另外我还有几个问题: 首先论文本身的 pdf 的内容是否可以复制, 即复制pdf的文字到其他地方是否出现乱码? 另外, tex
源文件的编码格式是什么?编译命令用了xelatex or pdflatex?

Qing jixiang <notifications@github.com> 于2019年9月29日周日 上午1:15写道：

**Comment by jikerWRN** [comment]
提供一种解决方案：Latex源码文件用GB2312编码+PDFLatex命令编译+使用ccmap包，亲测可用。

**Comment by lrtfm** [comment]
目前看来, 只要 PDF 文档的内容可复制, 且不是乱码, 即可正常查重.

使用 UTF-8 编码, 并使用 xelatex 命令编译, 生成的 pdf 文档可正常复制.  若复制还是乱码或全为问号, 请参考 README 中给出的解决方法.
