### ISSUE TITLE
怎么在模板里实现参考文献的上标引用和普通引用?

### ISSUE THREAD

**Issue by chxliu** [lrtfm/nputhesis#12]
试了下，%\usepackage[super]{natbib}
%\renewcommand\bibsection{\chapter*{\bibname}}还是报错，谢谢啦

**Comment by lrtfm** [comment]
@chxliu 请给出使用的编译命令和出错信息.

**Comment by lrtfm** [comment]
目前推荐的方式是使用 `biblatex` 宏包, 如 `sample.tex` 那样加载该宏包, 则 `\cite{XX}` 默认回显示为上标引用, `\parencite{XX}` 则为普通引用.
