### ISSUE TITLE
模板格式是否符合官方规定？

### ISSUE THREAD

**Issue by umbraclet16** [lrtfm/nputhesis#2]
首先，感谢分享。
关于格式，有些问题：

《西北工业大学 关于研究生学位论文撰写的规定》：

> 论文成品尺寸为:207mm ×290mm。页边距按以下标准设置:
> 上边距:天头至眉头 25 mm，下边距:页脚至地脚 25 mm，页眉至页脚:不大于 245 mm; 左、右边距为:30 mm，左右版心不大于 145 mm，居中，不留装订线。

看了眼cls文件，
```
\geometry{paperwidth=210mm,paperheight=297mm,%
  left=2.5cm,right=2.5cm,top=2.54cm,bottom=2.54cm}
```
似乎不太标准？手动改为标准参数，页面版式就破坏了，有些被挤到第二页。

另外，

> 中英文摘要、目录要单独用“I、II、II、IV”码编制页码。

应该需要多次重新计数，如**摘要I,II;目录I,II**等。

因为学位论文工作量都较大，大多数人都没有很好的修改格式的能力，如果最后发现格式不标准再转用word就很麻烦了。具体的字体、字号、段落、行间距等细节格式是否标准我没有能力确认，所以想求证一下，是否有人用这个模板提交论文并通过，谢谢！

**Comment by wyk-qyf** [comment]
1.摘要的罗马数字不需要重新计数，你看的规定可否发个链接？因为和我的不一样。
这是我在研究生院官网找的，应该官方。
[博士、硕士学位论文撰写规定.zip](https://github.com/lrtfm/nputhesis/files/1508527/default.zip)
2.段前和段后间距请问怎么调整，要求里都是0行。

**Comment by lrtfm** [comment]
1.  版式设置要求请参看你给出的 “西北工业大学博士研究生学位论文编写规则”  第6页。如果你需要改成其他参数，请发下你修改的参数和修改后的效果，我看看是什么问题。
2.  页码重新计数可以在摘要环境前和目录前添加命令 `\cleardoublepage\pagenumbering{Roman}`

**Comment by lrtfm** [comment]
3. 关于定理环境的段前、段后距离请使用下面设置
``` latex
\usepackage{amsthm}
\newtheoremstyle{nputheorem}% name
  {0pt}% Space above
  {0pt}% Space below
  {\itshape}% Body font
  {}% Indent amount
  {\bfseries}% Theorem head font
  {}% Punctuation after theorem head
  {.5em}% Space after theorem head
  {}% Theorem head spec (can be left empty, meaning ‘normal’ )

\theoremstyle{nputheorem}
\newtheorem{definition-chinese}{定义}
```

**Comment by wyk-qyf** [comment]
@lrtfm 大神好厉害，请问你是怎么学习的latex的格式设计，是看的官方每个包的英文帮助文档吗？我一直苦于找不到系统教授格式设计的学习资料，能否发一份让我学习下，最好是中文的。

**Comment by lrtfm** [comment]
@wyk-qyf 基本知识可以参考 *[刘海洋](https://github.com/leo-liu)* 编著的 《LaTeX 入门》。其次，就是参看个宏包的文档，一般都是宏包名加上 `.pdf`, 但是也有例外, 就像上面的 `amsthdoc.pdf`。(推荐安装软件 [Everything](http://www.voidtools.com/), 可以帮助寻找本机上安装的宏包文档)。

**Comment by wyk-qyf** [comment]
谢谢，我安装了everything，果然好用。《latex入门》这本书我也找来了，有问题就先去里面搜。
宏包的文档你都是直接看英文的吗？哪里有中文版吗？

发件人: Yang Zongze [mailto:notifications@github.com]
发送时间: 2017年11月29日 13:18
收件人: lrtfm/nputhesis <nputhesis@noreply.github.com>
抄送: Yufeng Qin <wyk_qyf@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [lrtfm/nputhesis] 模板格式是否符合官方规定？ (#2)


@wyk-qyf<https://github.com/wyk-qyf> 基本知识可以参考 刘海洋<https://github.com/leo-liu> 编著的 《LaTeX 入门》。其次，就是参看个宏包的文档，一般都是宏包名加上 .pdf, 但是也有例外, 就像上面的 amsthdoc.pdf。(推荐安装软件 Everything<http://www.voidtools.com/>, 可以帮助寻找本机上安装的宏包文档)。

**Comment by lrtfm** [comment]
1. 大部分宏包应该都有英文文档，中文的比较少，并且一般是处理中文排版的宏包才有中文文档。平时遇到的一些问题可以去问答平台提问或查找解决方法，如 [https://tex.stackexchange.com/](https://tex.stackexchange.com/)。
2. 除了在本机搜文档（使用 Everything 需要知道文档名或部分文档名），可以在 [CTAN](https://ctan.org/) 搜索相关文档（只需知道宏包名称）。

**Comment by lrtfm** [comment]
@umbraclet16 模板格式是按照学校给的文档定义的。有同学用过，应该没有大的问题。

**Comment by umbraclet16** [comment]
@lrtfm 不好意思，我又查了下学校的文件，压缩包里有两个文件，**西北工业大学博士研究生学位论文编写规则（试用版）**和**西北工业大学关于研究生学位论文撰写的规定**，里面要求并不一致。我上面引用的内容来自第二个，因为是要写**硕士**论文，没有看第一个文件。目前不太清楚两个文件还有多少不一致的地方。

按照我引用的格式编译，内封面最后一行的时间会被挤到下一页。
<img width="781" alt="default" src="https://user-images.githubusercontent.com/13113857/33404406-4f38dd00-d5b8-11e7-9f19-2fbb7ed121e0.png">

**Comment by lrtfm** [comment]
@umbraclet16  尝试修改 `nputhesis.cls` 第174行 `\vskip5cm` 和194行 `\par\vspace{4cm}`， 减小后面数值大小。把 `5` 和 `4` 改成 `4` 和 `3` 试试。

**Comment by wyk-qyf** [comment]
我有图是引用的，按要求需要在图题的右上角标出文献来源，我在figure环境下的\caption{}里用\cite{}，参考文献就不按引用顺序排序了，\caption里的\cite就变成[1]号文献了，求教大神

**Comment by wyk-qyf** [comment]
@lrtfm [我找到了一个答案，共同进步](https://stackoverflow.com/questions/4487728/latex-inserting-a-reference-in-a-figures-caption)
`\begin{figure}
  ...
  \caption[Cap for listoffigures]{Cap below figure with cite \cite{source}}
\end{figure}`
加入[短标题]即可使顺序正常，不明白为什么，只是能work，也许大神知道为什么，或许大神有更好的办法

**Comment by lrtfm** [comment]
@wyk-qyf 我这里使用 `xelatex` 编译的，没有问题。请问你的编译环境是什么？有添加了那些宏包？

原因不清楚，不过可参考 [protect-with-cite-inside-caption](https://tex.stackexchange.com/questions/174275/protect-with-cite-inside-caption) 的回答，可能是有的包重定义了 `cite` 命令导致的。

**Comment by wyk-qyf** [comment]
@lrtfm 我是texlive2017最新版，xelatex编译。我是添加了subfigure这个宏包，**只有**在子图里\cite才出问题，引用顺序就乱了。我加入[短标题]就能正常。可能是按您意思说subfigure这个包对cite命令不够鲁棒。

我依据刘海洋的《latex入门》换成subcaption宏包，在子图里\cite还是出问题，而且即使加入\caption[短标题]的**短标题选项**，还是不行，还不如原来的subfigure宏包。。。

所以我想请问大神在子图里加引用是用什么宏包？怎么设置的？

**Comment by lrtfm** [comment]
应该是 `natbib` 包的问题，参考 [insert-a-bibtex-reference-in-a-figure-caption](https://tex.stackexchange.com/questions/326467/insert-a-bibtex-reference-in-a-figure-caption).

**Comment by wyk-qyf** [comment]
@lrtfm 您好，忘了回复您了，本来以为natbib这种知名的宏包不会有这种bug。

我有一个新问题，我想添加内容进附录，我发现默认格式是按章节走的，学校要求是按如下要求的，请问应如何修改，自认为修改的地方是cls文件的
`\def\Appendix{\chapter{\npu@appendix}}`此处，但不知道如何修改。。论文马上要送审了，请指教，谢谢大神！

> 附  录 

> 附录是学位论文主体的补充，并不是必需的。`

> 附录编号依次编为附录A，附录B。附录标题各占一行，按一级标题编排。每一个附录一般应另起一页编排，如果有多个较短的附录，也可接排。

>

**Comment by lrtfm** [comment]
@wyk-qyf 
添加一个计数器，并使用 `\Alph` 把它的值转为字母。
```
\newcounter{npu@c@appendix}
\setcounter{npu@c@appendix}{0}
\def\Appendix{\addtocounter{npu@c@appendix}{1}\chapter{\npu@appendix\Alph{npu@c@appendix}}}
```

**Comment by wyk-qyf** [comment]
@lrtfm  我使用您默认的
`\bibliographystyle{bst/nputhesis}，`
发现不支持
`\usepackage[super,sort&compress,square,comma]{natbib}`
下的citet格式，请问如何修改，马上交论文了，求大神解答。
使用附件的bst文件，可以支持citet格式，但参考文献都多出来了
`[S.l.]: [s.n.],`如
`Wong W K, Moore A W, Cooper G F, et al. Bayesian network anomaly pattern de-
tection for disease outbreaks[C] // Proceedings of the 20th International Conference
on Machine Learning (ICML-03). [S.l.]: [s.n.], : 808–815.`
尽管多出来的符号是国标要求的，但是不想让它显示出来。求大神解答。
[numeric.zip](https://github.com/lrtfm/nputhesis/files/1591454/numeric.zip)

**Comment by wyk-qyf** [comment]
另外，封面右上角的内容，学校要求上是表格样式，您模版上没有加表格，请问如何加在封面上把右上角编程表格？定位到了cls文件里114行左右，求大神解答。
```
\begin{minipage}{\max@length}
        \makebox[\name@length][s]{\npu@schoolno}\npu@comma \@schoolno\\
        \makebox[\name@length][s]{\npu@classno}\npu@comma \@classno\\
        \makebox[\name@length][s]{\npu@secretlevel}\npu@comma \@secretlevel\\
        \makebox[\name@length][s]{\npu@authorno}\npu@comma \@authorno\\
\end{minipage}
```

**Comment by wyk-qyf** [comment]
```
% 摘要正文 宋体 小4号
% 一级标题和摘要 黑体 3号 20pt行距 段前段后0行
% 目录 宋体 小4号 行间距20pt
% 二级标题 黑体 4号 段前0.5行 段后0行 行间距20pt
% 三级标题 黑体 小4号 段前0.5行 行间距20pt
% 正文 宋体 小4号 行间距20pt
```

大神 这个格式问题最急了，求大神修改下cls， @lrtfm

**Comment by lrtfm** [comment]
@wyk-qyf 抱歉没能及时回复，不知问题是否修正？
1. 针对所使用 `numeric.zip`，可以修改其内容，让输出 `[S.l.]` 内容的部分输出为空。修改 如下
 `numeric.bst`文件789-794行
```
FUNCTION {format.sine.loco}
{ is.in.chinese
    { "[出版地不详]" }
    { "" }
  if$
}
```
799-704行,
```
FUNCTION {format.sine.nomine}
{ is.in.chinese
    { "[出版地不详]" }
    { "" }
  if$
}
```
825-830行
```
FUNCTION {format.sine.loco.sine.nomine}
{ is.in.chinese
    { "[出版地不详: 出版者不详]" }
    { "" }
  if$
}
```

2. 使用表格  todo.

3. 你使用了 `natbib`， 那么可以设置 `bibsep` 来修改`\setlength{\bibsep}{0pt plus 0.3ex}`。 Ref: https://tex.stackexchange.com/questions/93859/condense-the-space-between-bibliographic-entries

**Comment by wyk-qyf** [comment]
1. 这个问题我去尝试一下，谢谢回答
2. 这个封面我打算用word做一下凑合着
3.  1)参考文献按您的方法可以修改，谢谢。
 2)有个问题我没写全，下面是学校要求的格式，我看您模版上不太对，我按照自己的理解改了一下，请您指正，参看下面的代码：
```
% 摘要正文 宋体 小4号
% 一级标题和摘要 黑体 3号 20pt行距 段前段后0行  在一级标题前、后各留一空行（宋体，小4号，单倍行距）。
% 目录 宋体 小4号 行间距20pt
% 二级标题 黑体 4号 段前0.5行 段后0行 行间距20pt
% 三级标题 黑体 小4号 段前0.5行 行间距20pt
% 正文 宋体 小4号 行间距20pt
```
```
\ifx\ctexset\undefined
  \CTEXsetup[name={,}, number={\arabic{chapter}},beforeskip={0pt}, afterskip={10pt}]{chapter}
  \CTEXsetup[nameformat={\heiti\zihao{3}\bf}]{chapter}
  \CTEXsetup[titleformat={\heiti\zihao{3}}]{chapter}
  \CTEXsetup[format={\heiti\zihao{4}}]{section}
  \CTEXsetup[format={\heiti\zihao{-4}}]{subsection}
\else
%  \ctexset{chapter={name={,}, number={\arabic{chapter}},beforeskip={10pt}, afterskip={10pt}}}
  \ctexset{chapter={name={,}, number={\arabic{chapter}},beforeskip={14.4pt}, afterskip={14.4pt}}} % 一级标题和摘要 黑体 3号 20pt行距 段前段后0行 在一级标题前、后各留一空行（宋体，小4号 12pt，单倍行距 12*1.2=14.4）
  \ctexset{chapter={nameformat={\heiti\zihao{3}\bf}}}
  \ctexset{chapter={titleformat={\heiti\zihao{3}}}}
  \ctexset{section={format={\heiti\zihao{4}},beforeskip={10pt}, afterskip={0pt}}} % 二级标题 黑体 4号 段前0.5行 段后0行 行间距20pt
  \ctexset{subsection={format={\heiti\zihao{-4}},beforeskip={10pt}, afterskip={0pt}}} % 三级标题 黑体 小4号 段前0.5行 行间距20pt
\fi

\setlength{\abovecaptionskip}{10pt} %图标标题段前0.5行 也就是10pt
%\setlength{\belowcaptionskip}{10pt} %图标标题段后间距

```

**Comment by lrtfm** [comment]
@wyk-qyf 
1. 封面表格的内容，以更新到刚才的回复中。
2. 关于行距这块，word和latex的对应关系我不是很清楚。当时只是设置了大概的宽度。 
小四字体一般是12pt, 留一空行14.4pt应该是对的。如果按这个思路，section和subsection 的 beforeskip 应该再小些，设置为 7.2pt。个人感觉只要间距看起来舒服，这个影响不大。

**Comment by wyk-qyf** [comment]
使用numeric.bst，出现下列警告，论文的参考文献都没有年份，我推测是我的参考文献上的年份都属于date这个域，而year这个域是空的，而numeric.bst没有处理date这个域。 所以请问大神，如何增加numeric.bst 让它识别date这个域，或者把date这个域链接到year这个域，让它们等价也行。
`Warning--empty year in aloupis_geometric_2006`

**Comment by wyk-qyf** [comment]
@lrtfm 
1.封面表格我试试，谢谢
2.学校格式要求上是一级标题前后空一行 ，
`在一级标题前、后各留一空行（宋体，小4号，单倍行距）。`
此时行距是宋体小四单倍，所以是14.4pt。
但二级标题之后的要求变为`二级标题 黑体 4号 段前0.5行 段后0行 行间距20pt`，此时的段前0.5行我认为是按20pt来计算，所以是10pt，不是您说的按14.4pt计算出的7.2pt。
回答问题：
1. `nputhesis.bst`在使用`natbib`宏包后，正文若用`citet`来引用文献，编译后pdf上显示的是`“(author?) [21].”` 详见`natbib`的help文档，`The authors can only be listed if the .bst ﬁle supports author–year cita-
tions. The standard .bst ﬁles, such as plain.bst are numerical only and
transfer no author–year information to LATEX. In this case, \citet prints
“(author?) [21].”`
2. 不乱码

**Comment by lrtfm** [comment]
最简单的办法， 修改参考文献文件bib, 把date改为year.

**Comment by wyk-qyf** [comment]
@lrtfm 这个方法我只能最后尝试，因为我是用软件存的参考文献，下次再导出到bib文件后，会覆盖我上次手动修改的内容

**Comment by lrtfm** [comment]
对numeric代码做了些修改，你试下，看效果如何。
[numeric.zip](https://github.com/lrtfm/nputhesis/files/1594973/numeric.zip)

**Comment by wyk-qyf** [comment]
@lrtfm 封面表格我试了下 内容出来了 就是整个表格的位置跑到正中间了，原来是右上角的，请问大神如何修改下

**Comment by lrtfm** [comment]
修改时是不是加了空行？

**Comment by wyk-qyf** [comment]
@lrtfm 是的 删除空格后可以了，我又加了个`\flushright` 让表格更靠右了点， 谢谢大神 我再试试您的numeric.bst

**Comment by wyk-qyf** [comment]
@lrtfm 新的numeric.bst能够自动识别date域，谢谢您

**Comment by lrtfm** [comment]
@wyk-qyf 不客气，谢谢你的问题和建议。

**Comment by wyk-qyf** [comment]
@lrtfm 我使用了`hyperref`宏包，目录都是可以跳转到正确位置的，除了参考文献。参考文献会跳到最后一章的最后一节，请问是为什么呀？我也用了natbib
`\usepackage[super,sort&compress,square,comma]{natbib}%上标模式
\usepackage[colorlinks,linkcolor=black,anchorcolor=black,citecolor=black,urlcolor=black,bookmarksopen=true]{hyperref}%此宏包应放在所有宏包之后`

**Comment by lrtfm** [comment]
没有想到好的办法，下面是一个解决办法。
把 `cls` 文件中 （300--303行）
```
\let\npu@bibliographystyle\bibliographystyle
\def\bibliographystyle#1{%
  \addcontentsline{toc}{chapter}{\bibname}%
  \npu@bibliographystyle{#1}}
```
使用下面的代码替换掉
```
\renewenvironment{thebibliography}[1]
     {\chapter*{\bibname}\addcontentsline{toc}{chapter}{\bibname}%
      \@mkboth{\MakeUppercase\bibname}{\MakeUppercase\bibname}%
      \list{\@biblabel{\@arabic\c@enumiv}}%
           {\settowidth\labelwidth{\@biblabel{#1}}%
            \leftmargin\labelwidth
            \advance\leftmargin\labelsep
            \@openbib@code
            \usecounter{enumiv}%
            \let\p@enumiv\@empty
            \renewcommand\theenumiv{\@arabic\c@enumiv}}%
      \sloppy
      \clubpenalty4000
      \@clubpenalty \clubpenalty
      \widowpenalty4000%
      \sfcode`\.\@m}
     {\def\@noitemerr
       {\@latex@warning{Empty `thebibliography' environment}}%
      \endlist}
```

**Comment by umbraclet16** [comment]
请教：
有些页面因为之后的图或公式放不下就会存在较大的空白，然后这些空白被平均分到了段间距里，请问这种情况该怎么处理？段间距是不是该设置成固定值

**Comment by lrtfm** [comment]
@umbraclet16 
1. 图表是否使用了 `H` 选项固定位置，如果使用了，建议去掉。关于长公式，可以考虑中间加入可分页的命令, 即在公式换行命令 `\\` 前加入 `\displaybreak[2]`， 其中数字可以是 `0-4`, 0表示可以换页， 但尽量避免，4表示必须在此换页。也可在导言去加入 `allowdisplaybreaks[2]`, 使全文中多行公式都能够中间换页。但某些环境中，这两个命令不起作用 ，如`aligned`, `split`。可以把长工式分成多个公式。 
2. 请问是个别文献的问题，还是所有类型的文献都没有？

**Comment by umbraclet16** [comment]
@lrtfm 
似乎都出现在conference paper里。organization、volume、year之间没有分隔符。
就是IEEEvol.X20YY:page-page的效果。

Journal基本是正常的 year, volume(number):page-page格式。
偶尔有缺内容的会是year, :page-page这样。
Journal本身数据没有organization的项，有publisher但没显示，不影响。

**Comment by lrtfm** [comment]
1.  使用下面连接给出的`bst`文件， 修改了`conference `和 `inproceedings `的显示格式。看是否有还有其他问题。
[nputhesis.zip](https://github.com/lrtfm/nputhesis/files/1630311/nputhesis.zip)
2. 使用 tabularx 宏包， 其定义了列个是 X, 可以达到需要的效果， e.g. `\begin{tabularx}{\textwidth}{XX}`

**Comment by umbraclet16** [comment]
参考文献没有问题了。

另外一个问题是，每章最后的偶数页如果是空的话，页眉和页脚也不显示。

**Comment by umbraclet16** [comment]
从pdf里复制英文和数字出来后都变成空格，不知道是字体还是什么问题导致的。
这样查重时引用符号全都丢掉了，引用内容全都算重复，无法正常引用。。

**Comment by lrtfm** [comment]
@umbraclet16 请给出所用编译软件及版本，另外给出可复现问题的最小 tex 文件。

**Comment by umbraclet16** [comment]
不好意思，我发现这个问题是编译完用其他软件压缩导致的。

另，每章结尾偶数页为空时，如何显示页眉页脚？

**Comment by lrtfm** [comment]
打开文件 `nputhesis.cls`, 注释掉第 276 行, 即注释掉 `\thispagestyle{empty}`.

下面代码为上下文 267-278行
```tex
\def\cleardoublepage{\clearpage\if@twoside \ifodd\c@page\else
  \hbox{}
  \vspace*{\fill}
  \begin{center}\Large
    \if@npu@blankinfo
      \textcolor{gray!60}{This Page Intentionally Left Blank!}
    \fi
  \end{center}
  \vspace{\fill}
  \thispagestyle{empty}
  \newpage
  \if@twocolumn\hbox{}\newpage\fi\fi\fi}
```
改为
```tex
\def\cleardoublepage{\clearpage\if@twoside \ifodd\c@page\else
  \hbox{}
  \vspace*{\fill}
  \begin{center}\Large
    \if@npu@blankinfo
      \textcolor{gray!60}{This Page Intentionally Left Blank!}
    \fi
  \end{center}
  \vspace{\fill}
  %\thispagestyle{empty}
  \newpage
  \if@twocolumn\hbox{}\newpage\fi\fi\fi}
```
