### ISSUE TITLE
编译出来会目录部分出现重复的   目录？

### ISSUE THREAD

**Issue by wangsen1312** [lrtfm/nputhesis#3]
![test](https://user-images.githubusercontent.com/11545246/37500154-d13d6fa8-2902-11e8-9736-30e8cd727790.png)

请问有什么好的解决方式么？ 
谢谢~

**Comment by lrtfm** [comment]
@wangsen1312 请给出所用编译环境，及相关代码。

**Comment by wangsen1312** [comment]
@lrtfm  
我用的是win10  Texlive 2017 直接编译   代码就是你的example code~

**Comment by lrtfm** [comment]
谢谢，已修复， 相关更改请点击链接 [5620a7](https://github.com/lrtfm/nputhesis/commit/5620a798fdc01036925c4d89cf31614203a9638e)

**Comment by arctanx** [comment]
修复了参考文献跳转错误之后，目录中包含参考文献的那一页的页眉会显示“参考文献”，而不是“目录”。请问怎么解决？
Win7 texlive2017

**Comment by lrtfm** [comment]
@arctanx 请尝试清除临时文件,  并下载最新 `.cls` 文件, 重新编译, 看问题是否依旧存在. 如果存在, 请给出可复现问题的最小相关代码.

**Comment by arctanx** [comment]
sorry 回复晚了，我找到目录页眉显示“参考文献”问题的根源了。为了让正文中引用参考文献以上标形式显示，在 sample.tex 中 \usepackage[super]{natbib}。使用官方的文件，就可以复现这个问题。win7+texlive2017

**Comment by lrtfm** [comment]
在 `natbib.sty` 中, 重新定义了 `\bibsection` 命令, 在章节名称中使用了 `markboth`, 所以导致出现上述问题. 
```
\renewcommand\bibsection{%
   \chapter*{\bibname\@mkboth{\MakeUppercase{\bibname}}{\MakeUppercase{\bibname}}}%
 }%
```
修复方式: 在使用 `natbib` 包时, 修改上述 `bibsection` 命令可修复上述问题
```
\usepackage[super]{natbib}
\renewcommand\bibsection{\chapter*{\bibname}}
