### ISSUE TITLE
首页右上角的边框

### ISSUE THREAD

**Issue by johnvon** [lrtfm/nputhesis#4]
按照要求，首页右上角的学校代码等信息应该是有边框的，类似下面的样子，不知这个该如何修改？

| **学校代码**         | **10699** |
| -------------------- | --------- |
| **分** **类** **号** |           |
| **密**    **级**     |           |
| **学**    **号**     |           |

**Comment by lrtfm** [comment]
已添加表格边框. [修改](https://github.com/lrtfm/nputhesis/commit/5724c6353af99952f69d6582c3747bee2497f17d)

**Comment by johnvon** [comment]
实际上，此处的\begin{minipage}{\max@length}中的\max@length定义的长度是不够的，这回造成添加表格之后的竖线和横线的相交处是断开的。最简单的修改是将上述宽度增加一点，例如：
将\settowidth{\max@length}{\npu@schoolno\npu@comma 2000000000}修改为\settowidth{\max@length}{\npu@schoolno\npu@comma 200000000000}。

**Comment by lrtfm** [comment]
已修复.
