### ISSUE TITLE
中文参考文献，三人以上时，et al. 如何修改为 等

### ISSUE THREAD

**Issue by arctanx** [lrtfm/nputhesis#5]
如题，需要修改 bst 文件吗，不知如何下手。

**Comment by lrtfm** [comment]
请试下下面的 bst 文件 [numeric 格式文件](https://github.com/lrtfm/nputhesis/files/1594973/numeric.zip)

**Comment by johnvon** [comment]
推荐使用biblatex的gb7714-2015样式管理参考文献，详见biblatex宏包的文档（有中译版），gb7714-2015样式本身是中文文档。

**Comment by lrtfm** [comment]
@johnvon 谢谢建议。

**Comment by lrtfm** [comment]
sample 已默认使用 [biblatex-gb7714-2015](https://github.com/hushidong/biblatex-gb7714-2015).
