### ISSUE TITLE
页眉是否可以加上 第几章 ？

### ISSUE THREAD

**Issue by wangsen1312** [lrtfm/nputhesis#7]
现在的页眉在奇数页只有 本章的名字 没有第几章  不知道是否有什么解决办法  谢谢~

**Comment by lrtfm** [comment]
奇数页已添加章节号

**Comment by wangsen1312** [comment]
<img width="496" alt="capture" src="https://user-images.githubusercontent.com/11545246/39042167-c382330a-44bc-11e8-8f94-81e58427f36f.PNG">
<img width="514" alt="capture1" src="https://user-images.githubusercontent.com/11545246/39042169-c3b9329c-44bc-11e8-8a42-ff6c925e9bd3.PNG">

谢谢增加了号码~ 我想知道这个数字改成中文好改么？ 应该在哪里处理 谢谢~

**Comment by wangsen1312** [comment]
还有一个问题 最新的版本 我自己编译 会出现下面的问题 我感觉是cls 文件的第39行有问题
<img width="303" alt="capture" src="https://user-images.githubusercontent.com/11545246/39043849-0c4ad0c0-44c1-11e8-954e-299138e7943f.PNG">
<img width="194" alt="capture1" src="https://user-images.githubusercontent.com/11545246/39043850-0c9e1046-44c1-11e8-98a8-934ed78a1f64.PNG">

初学者 还不是看的很懂 我下来会恶补一下 谢谢~

**Comment by wangsen1312** [comment]
@lrtfm Windows 10 pro   tex 2017~

谢谢~

**Comment by lrtfm** [comment]
应该有错误信息的, 因为你使用 `pdflatex`编译. 而上面的命令是 `xelatex` 提供的. 所以出错了. 推荐用 `xelatex` 进行编译. 如果使用 `pdflatex`, 删掉就可以, 也可以做如下修改(39行)
```
\RequirePackage{ifxetex}
\ifxetex
  \setmainfont{Times New Roman}
\fi
```
