### ISSUE TITLE
一级标题不符合官方要求

### ISSUE THREAD

**Issue by 6Charles** [lrtfm/nputhesis#9]
感谢作者的辛勤付出！！！

模板里面的一级标题是“**第一章 绪论**”的样式。
官方要求“西北工业大学博士研究生学位论文编写规则（试用版）”中要求采用“**1 绪论**”这种样式，如下

![image](https://user-images.githubusercontent.com/31790716/48659468-aa670780-ea8c-11e8-8a6f-44239023ce8f.png)

此外，**samples.tex中的“符号命名表”**，在win10，TexLive2018-XeLatex下编译了几次会在目录后面编译出空白页，但是没有符号命名表。

再次感谢！

**Comment by lrtfm** [comment]
1）关于章节标题格式， 我感觉中文使用 `第一章` 这种更好一些。
如果需要修改， 请在导言区加上
```
\ifx\ctexset\undefined
  \CTEXsetup[name={,}, number={\arabic{chapter}},
    beforeskip={20pt}, afterskip={20pt}]{chapter}
\else
  \ctexset{
    chapter/name={,},                
    chapter/number=\arabic{chapter},
    chapter/beforeskip={20bp},
    chapter/afterskip={20bp},
    chapter/format={\heiti\zihao{3}\centering}
  }
\fi
```
或者取消 文件 `nputhesis.cls` 第[51,63,64](https://github.com/lrtfm/nputhesis/blob/bdf18ae978b3050ddd9b7d955624531948b12a94/nputhesis.cls#L51)行的第一个注释符号.
2) 有符号表的编译请参考[如何使用](https://github.com/lrtfm/nputhesis#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8). 请给出你使用的编译命令

**Comment by lrtfm** [comment]
基于中文习惯, 个人觉得使用 "第一章" 这样的更符合中文习惯, 故模板未做改动.
